name: RDS Compliance Detection

on:
  workflow_dispatch:
    inputs:
      regions:
        description: "Comma-separated AWS regions"
        required: true
        default: "eu-west-1"
      accounts:
        description: "Comma-separated role ARNs to assume (one per account)"
        required: true
  schedule:
    - cron: "0 3 * * *"  # daily 03:00 UTC

permissions:
  id-token: write
  contents: read

jobs:
  detect:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        region: ${{ fromJson(inputs.regions && format('["{0}"]', inputs.regions) || '["eu-west-1"]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Parse accounts
        id: parse
        shell: bash
        run: |
          echo "accounts=$(echo '${{ inputs.accounts }}' | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | jq -R -s -c 'split("\n")|map(select(length>0))')" >> $GITHUB_OUTPUT
      - name: Detect per account
        shell: bash
        run: |
          mkdir -p reports
          accounts='${{ steps.parse.outputs.accounts }}'
          for role_arn in $(echo "$accounts" | jq -r '.[]'); do
            acct=$(echo "$role_arn" | awk -F: '{print $5}')
            python ./dam-detection.py \
              --baseline baselines/rds-baseline.json \
              --region "${{ matrix.region }}" \
              --account-role-arn "$role_arn" \
              --check-log-groups \
              --output "reports/detect-${acct}-${{ matrix.region }}.json" || true
          done
      - uses: actions/upload-artifact@v4
        with:
          name: detect-reports
          path: reports/
