name: RDS Compliance Remediation

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region"
        required: true
        default: "eu-west-1"
      account_role_arn:
        description: "Role ARN to assume in the target account"
        required: true
      report_artifact_name:
        description: "Artifact name containing detection report"
        required: true
        default: "detect-reports"
      report_file:
        description: "Which report file to use from the artifact"
        required: true
      apply:
        description: "Apply changes (true) or dry-run (false)"
        required: true
        default: "false"

permissions:
  id-token: write
  contents: read

jobs:
  remediate:
    runs-on: ubuntu-latest
    environment:
      name: remediation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.report_artifact_name }}
          path: reports
      - name: Dry-run remediation (preview)
        run: |
          python ./dam-remediation.py \
            --baseline baselines/rds-baseline.json \
            --report "reports/${{ inputs.report_file }}" \
            --region "${{ inputs.region }}" \
            --account-role-arn "${{ inputs.account_role_arn }}" \
            --ensure-log-groups
      - name: Apply remediation (set apply=true)
        if: ${{ inputs.apply == 'true' }}
        run: |
          python ./dam-remediation.py \
            --baseline baselines/rds-baseline.json \
            --report "reports/${{ inputs.report_file }}" \
            --region "${{ inputs.region }}" \
            --account-role-arn "${{ inputs.account_role_arn }}" \
            --apply \
            --ensure-log-groups
